# fly.toml app configuration file generated for ovatify-backend on 2023-11-08T22:21:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ovatify-backend"
primary_region = "ams"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  DJANGO_SETTINGS_MODULE = "OVTF_Backend.settings"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
