# fly.toml app configuration file generated for ovatify-backend-dev on 2023-11-08T20:50:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ovatify-backend-dev"
primary_region = "ams"
console_command = "/code/manage.py shell"

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "OVTF_Backend.settings"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
