# Generated by Django 4.2.7 on 2023-11-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_instrument_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
