# Generated by Django 4.2.7 on 2023-11-18 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_song_albums_song_artists_song_genres_and_more'),
        ('users', '0004_alter_user_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='users.Friend', to='users.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='ratings',
            field=models.ManyToManyField(through='users.UserSongRating', to='songs.song'),
        ),
        migrations.RemoveField(
            model_name='usersongrating',
            name='date_rated',
        ),
        migrations.AddField(
            model_name='user',
            name='user_preferences',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.userpreferences'),
        ),
    ]
