# Generated by Django 4.2.7 on 2023-11-18 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_usersongrating_date_rated_user_friends_and_more'),
    ]

    operations = [
    ]
