# Generated by Django 4.2.7 on 2023-11-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usersongrating_date_rated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ratings',
        ),
    ]
