# Generated by Django 4.2.7 on 2023-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='data_processing_consent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='data_sharing_consent',
            field=models.BooleanField(default=True),
        ),
    ]
