# Generated by Django 4.2.7 on 2023-11-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_song_albums_song_artists_song_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
