# Generated by Django 4.2.7 on 2023-11-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_rename_title_album_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='release_date',
        ),
        migrations.AddField(
            model_name='album',
            name='release_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
