# Generated by Django 4.2.7 on 2023-11-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
