# Generated by Django 4.2.7 on 2023-12-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='img_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='img_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='img_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='img_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
